/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVendasIndexRouteImport } from './routes/app/vendas/index'
import { Route as AppVeiculosIndexRouteImport } from './routes/app/veiculos/index'
import { Route as AppUsuariosIndexRouteImport } from './routes/app/usuarios/index'
import { Route as AppOsIndexRouteImport } from './routes/app/os/index'
import { Route as AppFornecedoresIndexRouteImport } from './routes/app/fornecedores/index'
import { Route as AppEstoqueIndexRouteImport } from './routes/app/estoque/index'
import { Route as AppClientesIndexRouteImport } from './routes/app/clientes/index'
import { Route as AppVendasNovaRouteImport } from './routes/app/vendas/nova'
import { Route as AppVeiculosPlacaRouteImport } from './routes/app/veiculos/$placa'
import { Route as AppOsNovaRouteImport } from './routes/app/os/nova'
import { Route as AppOsOsIdRouteImport } from './routes/app/os/$osId'
import { Route as AppFornecedoresFornecedorIdRouteImport } from './routes/app/fornecedores/$fornecedorId'
import { Route as AppEstoqueEntradasRouteImport } from './routes/app/estoque/entradas'
import { Route as AppClientesClienteIdRouteImport } from './routes/app/clientes/$clienteId'
import { Route as AppCadastrosMarcasRouteImport } from './routes/app/cadastros/marcas'
import { Route as AppEstoqueNfeRevisaoRascunhoIdRouteImport } from './routes/app/estoque/nfe-revisao.$rascunhoId'
import { Route as AppEstoqueEntradaEntradaIdRouteImport } from './routes/app/estoque/entrada/$entradaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIndexRoute = AppVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppOsIndexRoute = AppOsIndexRouteImport.update({
  id: '/os/',
  path: '/os/',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresIndexRoute = AppFornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueIndexRoute = AppEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasNovaRoute = AppVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosPlacaRoute = AppVeiculosPlacaRouteImport.update({
  id: '/veiculos/$placa',
  path: '/veiculos/$placa',
  getParentRoute: () => AppRoute,
} as any)
const AppOsNovaRoute = AppOsNovaRouteImport.update({
  id: '/os/nova',
  path: '/os/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppOsOsIdRoute = AppOsOsIdRouteImport.update({
  id: '/os/$osId',
  path: '/os/$osId',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresFornecedorIdRoute =
  AppFornecedoresFornecedorIdRouteImport.update({
    id: '/fornecedores/$fornecedorId',
    path: '/fornecedores/$fornecedorId',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstoqueEntradasRoute = AppEstoqueEntradasRouteImport.update({
  id: '/estoque/entradas',
  path: '/estoque/entradas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AppRoute,
} as any)
const AppCadastrosMarcasRoute = AppCadastrosMarcasRouteImport.update({
  id: '/cadastros/marcas',
  path: '/cadastros/marcas',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueNfeRevisaoRascunhoIdRoute =
  AppEstoqueNfeRevisaoRascunhoIdRouteImport.update({
    id: '/estoque/nfe-revisao/$rascunhoId',
    path: '/estoque/nfe-revisao/$rascunhoId',
    getParentRoute: () => AppRoute,
  } as any)
const AppEstoqueEntradaEntradaIdRoute =
  AppEstoqueEntradaEntradaIdRouteImport.update({
    id: '/estoque/entrada/$entradaId',
    path: '/estoque/entrada/$entradaId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/cadastros/marcas': typeof AppCadastrosMarcasRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/fornecedores/$fornecedorId': typeof AppFornecedoresFornecedorIdRoute
  '/app/os/$osId': typeof AppOsOsIdRoute
  '/app/os/nova': typeof AppOsNovaRoute
  '/app/veiculos/$placa': typeof AppVeiculosPlacaRoute
  '/app/vendas/nova': typeof AppVendasNovaRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/estoque/': typeof AppEstoqueIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/os/': typeof AppOsIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/vendas/': typeof AppVendasIndexRoute
  '/app/estoque/entrada/$entradaId': typeof AppEstoqueEntradaEntradaIdRoute
  '/app/estoque/nfe-revisao/$rascunhoId': typeof AppEstoqueNfeRevisaoRascunhoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/cadastros/marcas': typeof AppCadastrosMarcasRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/fornecedores/$fornecedorId': typeof AppFornecedoresFornecedorIdRoute
  '/app/os/$osId': typeof AppOsOsIdRoute
  '/app/os/nova': typeof AppOsNovaRoute
  '/app/veiculos/$placa': typeof AppVeiculosPlacaRoute
  '/app/vendas/nova': typeof AppVendasNovaRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/estoque': typeof AppEstoqueIndexRoute
  '/app/fornecedores': typeof AppFornecedoresIndexRoute
  '/app/os': typeof AppOsIndexRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
  '/app/vendas': typeof AppVendasIndexRoute
  '/app/estoque/entrada/$entradaId': typeof AppEstoqueEntradaEntradaIdRoute
  '/app/estoque/nfe-revisao/$rascunhoId': typeof AppEstoqueNfeRevisaoRascunhoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/cadastros/marcas': typeof AppCadastrosMarcasRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/fornecedores/$fornecedorId': typeof AppFornecedoresFornecedorIdRoute
  '/app/os/$osId': typeof AppOsOsIdRoute
  '/app/os/nova': typeof AppOsNovaRoute
  '/app/veiculos/$placa': typeof AppVeiculosPlacaRoute
  '/app/vendas/nova': typeof AppVendasNovaRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/estoque/': typeof AppEstoqueIndexRoute
  '/app/fornecedores/': typeof AppFornecedoresIndexRoute
  '/app/os/': typeof AppOsIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
  '/app/vendas/': typeof AppVendasIndexRoute
  '/app/estoque/entrada/$entradaId': typeof AppEstoqueEntradaEntradaIdRoute
  '/app/estoque/nfe-revisao/$rascunhoId': typeof AppEstoqueNfeRevisaoRascunhoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/cadastros/marcas'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/fornecedores/$fornecedorId'
    | '/app/os/$osId'
    | '/app/os/nova'
    | '/app/veiculos/$placa'
    | '/app/vendas/nova'
    | '/app/clientes/'
    | '/app/estoque/'
    | '/app/fornecedores/'
    | '/app/os/'
    | '/app/usuarios/'
    | '/app/veiculos/'
    | '/app/vendas/'
    | '/app/estoque/entrada/$entradaId'
    | '/app/estoque/nfe-revisao/$rascunhoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/cadastros/marcas'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/fornecedores/$fornecedorId'
    | '/app/os/$osId'
    | '/app/os/nova'
    | '/app/veiculos/$placa'
    | '/app/vendas/nova'
    | '/app/clientes'
    | '/app/estoque'
    | '/app/fornecedores'
    | '/app/os'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/vendas'
    | '/app/estoque/entrada/$entradaId'
    | '/app/estoque/nfe-revisao/$rascunhoId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/cadastros/marcas'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/fornecedores/$fornecedorId'
    | '/app/os/$osId'
    | '/app/os/nova'
    | '/app/veiculos/$placa'
    | '/app/vendas/nova'
    | '/app/clientes/'
    | '/app/estoque/'
    | '/app/fornecedores/'
    | '/app/os/'
    | '/app/usuarios/'
    | '/app/veiculos/'
    | '/app/vendas/'
    | '/app/estoque/entrada/$entradaId'
    | '/app/estoque/nfe-revisao/$rascunhoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas/': {
      id: '/app/vendas/'
      path: '/vendas'
      fullPath: '/app/vendas/'
      preLoaderRoute: typeof AppVendasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/veiculos'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios/': {
      id: '/app/usuarios/'
      path: '/usuarios'
      fullPath: '/app/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/os/': {
      id: '/app/os/'
      path: '/os'
      fullPath: '/app/os/'
      preLoaderRoute: typeof AppOsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores/': {
      id: '/app/fornecedores/'
      path: '/fornecedores'
      fullPath: '/app/fornecedores/'
      preLoaderRoute: typeof AppFornecedoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/': {
      id: '/app/estoque/'
      path: '/estoque'
      fullPath: '/app/estoque/'
      preLoaderRoute: typeof AppEstoqueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas/nova': {
      id: '/app/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/app/vendas/nova'
      preLoaderRoute: typeof AppVendasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/$placa': {
      id: '/app/veiculos/$placa'
      path: '/veiculos/$placa'
      fullPath: '/app/veiculos/$placa'
      preLoaderRoute: typeof AppVeiculosPlacaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/os/nova': {
      id: '/app/os/nova'
      path: '/os/nova'
      fullPath: '/app/os/nova'
      preLoaderRoute: typeof AppOsNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/os/$osId': {
      id: '/app/os/$osId'
      path: '/os/$osId'
      fullPath: '/app/os/$osId'
      preLoaderRoute: typeof AppOsOsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fornecedores/$fornecedorId': {
      id: '/app/fornecedores/$fornecedorId'
      path: '/fornecedores/$fornecedorId'
      fullPath: '/app/fornecedores/$fornecedorId'
      preLoaderRoute: typeof AppFornecedoresFornecedorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/entradas': {
      id: '/app/estoque/entradas'
      path: '/estoque/entradas'
      fullPath: '/app/estoque/entradas'
      preLoaderRoute: typeof AppEstoqueEntradasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$clienteId': {
      id: '/app/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/app/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cadastros/marcas': {
      id: '/app/cadastros/marcas'
      path: '/cadastros/marcas'
      fullPath: '/app/cadastros/marcas'
      preLoaderRoute: typeof AppCadastrosMarcasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/nfe-revisao/$rascunhoId': {
      id: '/app/estoque/nfe-revisao/$rascunhoId'
      path: '/estoque/nfe-revisao/$rascunhoId'
      fullPath: '/app/estoque/nfe-revisao/$rascunhoId'
      preLoaderRoute: typeof AppEstoqueNfeRevisaoRascunhoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/entrada/$entradaId': {
      id: '/app/estoque/entrada/$entradaId'
      path: '/estoque/entrada/$entradaId'
      fullPath: '/app/estoque/entrada/$entradaId'
      preLoaderRoute: typeof AppEstoqueEntradaEntradaIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCadastrosMarcasRoute: typeof AppCadastrosMarcasRoute
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppEstoqueEntradasRoute: typeof AppEstoqueEntradasRoute
  AppFornecedoresFornecedorIdRoute: typeof AppFornecedoresFornecedorIdRoute
  AppOsOsIdRoute: typeof AppOsOsIdRoute
  AppOsNovaRoute: typeof AppOsNovaRoute
  AppVeiculosPlacaRoute: typeof AppVeiculosPlacaRoute
  AppVendasNovaRoute: typeof AppVendasNovaRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppEstoqueIndexRoute: typeof AppEstoqueIndexRoute
  AppFornecedoresIndexRoute: typeof AppFornecedoresIndexRoute
  AppOsIndexRoute: typeof AppOsIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
  AppVendasIndexRoute: typeof AppVendasIndexRoute
  AppEstoqueEntradaEntradaIdRoute: typeof AppEstoqueEntradaEntradaIdRoute
  AppEstoqueNfeRevisaoRascunhoIdRoute: typeof AppEstoqueNfeRevisaoRascunhoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCadastrosMarcasRoute: AppCadastrosMarcasRoute,
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppEstoqueEntradasRoute: AppEstoqueEntradasRoute,
  AppFornecedoresFornecedorIdRoute: AppFornecedoresFornecedorIdRoute,
  AppOsOsIdRoute: AppOsOsIdRoute,
  AppOsNovaRoute: AppOsNovaRoute,
  AppVeiculosPlacaRoute: AppVeiculosPlacaRoute,
  AppVendasNovaRoute: AppVendasNovaRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppEstoqueIndexRoute: AppEstoqueIndexRoute,
  AppFornecedoresIndexRoute: AppFornecedoresIndexRoute,
  AppOsIndexRoute: AppOsIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
  AppVendasIndexRoute: AppVendasIndexRoute,
  AppEstoqueEntradaEntradaIdRoute: AppEstoqueEntradaEntradaIdRoute,
  AppEstoqueNfeRevisaoRascunhoIdRoute: AppEstoqueNfeRevisaoRascunhoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
