/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVeiculosIndexRouteImport } from './routes/app/veiculos/index'
import { Route as AppUsuariosIndexRouteImport } from './routes/app/usuarios/index'
import { Route as AppEstoqueIndexRouteImport } from './routes/app/estoque/index'
import { Route as AppClientesIndexRouteImport } from './routes/app/clientes/index'
import { Route as AppEstoqueEntradasRouteImport } from './routes/app/estoque/entradas'
import { Route as AppClientesClienteIdRouteImport } from './routes/app/clientes/$clienteId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVeiculosIndexRoute = AppVeiculosIndexRouteImport.update({
  id: '/veiculos/',
  path: '/veiculos/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueIndexRoute = AppEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueEntradasRoute = AppEstoqueEntradasRouteImport.update({
  id: '/estoque/entradas',
  path: '/estoque/entradas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesClienteIdRoute = AppClientesClienteIdRouteImport.update({
  id: '/clientes/$clienteId',
  path: '/clientes/$clienteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/estoque/': typeof AppEstoqueIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/clientes': typeof AppClientesIndexRoute
  '/app/estoque': typeof AppEstoqueIndexRoute
  '/app/usuarios': typeof AppUsuariosIndexRoute
  '/app/veiculos': typeof AppVeiculosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/app/clientes/$clienteId': typeof AppClientesClienteIdRoute
  '/app/estoque/entradas': typeof AppEstoqueEntradasRoute
  '/app/clientes/': typeof AppClientesIndexRoute
  '/app/estoque/': typeof AppEstoqueIndexRoute
  '/app/usuarios/': typeof AppUsuariosIndexRoute
  '/app/veiculos/': typeof AppVeiculosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/clientes/'
    | '/app/estoque/'
    | '/app/usuarios/'
    | '/app/veiculos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/clientes'
    | '/app/estoque'
    | '/app/usuarios'
    | '/app/veiculos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/'
    | '/app/clientes/$clienteId'
    | '/app/estoque/entradas'
    | '/app/clientes/'
    | '/app/estoque/'
    | '/app/usuarios/'
    | '/app/veiculos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/veiculos/': {
      id: '/app/veiculos/'
      path: '/veiculos'
      fullPath: '/app/veiculos/'
      preLoaderRoute: typeof AppVeiculosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios/': {
      id: '/app/usuarios/'
      path: '/usuarios'
      fullPath: '/app/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/': {
      id: '/app/estoque/'
      path: '/estoque'
      fullPath: '/app/estoque/'
      preLoaderRoute: typeof AppEstoqueIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/': {
      id: '/app/clientes/'
      path: '/clientes'
      fullPath: '/app/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque/entradas': {
      id: '/app/estoque/entradas'
      path: '/estoque/entradas'
      fullPath: '/app/estoque/entradas'
      preLoaderRoute: typeof AppEstoqueEntradasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes/$clienteId': {
      id: '/app/clientes/$clienteId'
      path: '/clientes/$clienteId'
      fullPath: '/app/clientes/$clienteId'
      preLoaderRoute: typeof AppClientesClienteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientesClienteIdRoute: typeof AppClientesClienteIdRoute
  AppEstoqueEntradasRoute: typeof AppEstoqueEntradasRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppEstoqueIndexRoute: typeof AppEstoqueIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
  AppVeiculosIndexRoute: typeof AppVeiculosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientesClienteIdRoute: AppClientesClienteIdRoute,
  AppEstoqueEntradasRoute: AppEstoqueEntradasRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppEstoqueIndexRoute: AppEstoqueIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
  AppVeiculosIndexRoute: AppVeiculosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
