from enum import Enum


class TipoAgente(str, Enum):
    PRODUTOR_RURAL = "PRODUTOR_RURAL"
    INDUSTRIAL = "INDUSTRIAL"
    ARTESAO = "ARTESAO"
    CONSULTOR_TECNICO = "CONSULTOR_TECNICO"
    OPERADOR = "OPERADOR"
    CONSUMIDOR = "CONSUMIDOR"
    ADMIN_PLATAFORMA = "ADMIN_PLATAFORMA"


class PlanoAssinatura(str, Enum):
    FREE = "FREE"
    CORE_PLUS = "CORE_PLUS"
    PREMIUM_AGRO = "PREMIUM_AGRO"
    INDUSTRIA_BASIC = "INDUSTRIA_BASIC"
    INDUSTRIA_PRO = "INDUSTRIA_PRO"
    COOPERATIVA = "COOPERATIVA"


class TipoUnidade(str, Enum):
    TALHAO = "TALHAO"
    LINHA_PRODUCAO = "LINHA_PRODUCAO"
    TEAR = "TEAR"
    ATELIE = "ATELIE"
    BAIA = "BAIA"
    VIVEIRO = "VIVEIRO"
    OUTRO = "OUTRO"


class StatusCiclo(str, Enum):
    ABERTO = "ABERTO"
    EM_PRODUCAO = "EM_PRODUCAO"
    ENCERRADO = "ENCERRADO"
    VALIDANDO = "VALIDANDO"
    LOTE_GERADO = "LOTE_GERADO"
    ARQUIVADO = "ARQUIVADO"


class TipoEvento(str, Enum):
    ENTRADA_INSUMO = "ENTRADA_INSUMO"
    OPERACAO = "OPERACAO"
    CTRL_QUALIDADE = "CTRL_QUALIDADE"
    ANOMALIA = "ANOMALIA"
    MOVIMENTACAO = "MOVIMENTACAO"
    COLHEITA = "COLHEITA"
    EXPEDICAO = "EXPEDICAO"


class StatusValidacao(str, Enum):
    PENDENTE = "PENDENTE"
    VALIDADO = "VALIDADO"
    INVALIDO = "INVALIDO"
    ADITADO = "ADITADO"


class OrigemCaptura(str, Enum):
    VOZ = "VOZ"
    FOTO = "FOTO"
    QR_SCAN = "QR_SCAN"
    MANUAL = "MANUAL"
    API = "API"


class StatusLote(str, Enum):
    GERADO = "GERADO"
    PUBLICADO = "PUBLICADO"
    SUSPENSO = "SUSPENSO"
    REVOGADO = "REVOGADO"


class EstadoAgente(str, Enum):
    OCIOSO = "OCIOSO"
    ESCUTANDO = "ESCUTANDO"
    PROCESSANDO = "PROCESSANDO"
    AGUARD_CONFIRM = "AGUARD_CONFIRM"
    SINCRONIZANDO = "SINCRONIZANDO"
    OFFLINE = "OFFLINE"


class CategoriaKb(str, Enum):
    INSUMO = "INSUMO"
    OPERACAO = "OPERACAO"
    CONTROLE_QUALIDADE = "CONTROLE_QUALIDADE"
    ANOMALIA = "ANOMALIA"
    COLHEITA = "COLHEITA"
    MOVIMENTACAO = "MOVIMENTACAO"


class RolePerfil(str, Enum):
    PRODUTOR = "PRODUTOR"
    OPERADOR = "OPERADOR"
    CONSULTOR = "CONSULTOR"
    ADMIN = "ADMIN"
    CONSUMIDOR = "CONSUMIDOR"


class TipoAsset(str, Enum):
    QR_PNG = "QR_PNG"
    QR_SVG = "QR_SVG"
    CERTIFICADO_PDF = "CERTIFICADO_PDF"
