/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaAreaIndexRouteImport } from './routes/minha-area/index'
import { Route as PHashRouteImport } from './routes/p.$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAreaIndexRoute = MinhaAreaIndexRouteImport.update({
  id: '/minha-area/',
  path: '/minha-area/',
  getParentRoute: () => rootRouteImport,
} as any)
const PHashRoute = PHashRouteImport.update({
  id: '/p/$hash',
  path: '/p/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$hash': typeof PHashRoute
  '/minha-area/': typeof MinhaAreaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$hash': typeof PHashRoute
  '/minha-area': typeof MinhaAreaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$hash': typeof PHashRoute
  '/minha-area/': typeof MinhaAreaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$hash' | '/minha-area/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$hash' | '/minha-area'
  id: '__root__' | '/' | '/p/$hash' | '/minha-area/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PHashRoute: typeof PHashRoute
  MinhaAreaIndexRoute: typeof MinhaAreaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-area/': {
      id: '/minha-area/'
      path: '/minha-area'
      fullPath: '/minha-area/'
      preLoaderRoute: typeof MinhaAreaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$hash': {
      id: '/p/$hash'
      path: '/p/$hash'
      fullPath: '/p/$hash'
      preLoaderRoute: typeof PHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PHashRoute: PHashRoute,
  MinhaAreaIndexRoute: MinhaAreaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
