/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWhatsappIndexRouteImport } from './routes/dashboard/whatsapp/index'
import { Route as DashboardUsuariosIndexRouteImport } from './routes/dashboard/usuarios/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardRegistrosIndexRouteImport } from './routes/dashboard/registros/index'
import { Route as DashboardWhatsappSessionIdRouteImport } from './routes/dashboard/whatsapp/$sessionId'
import { Route as DashboardUsuariosNovoRouteImport } from './routes/dashboard/usuarios/novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappIndexRoute = DashboardWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsuariosIndexRoute = DashboardUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRegistrosIndexRoute = DashboardRegistrosIndexRouteImport.update({
  id: '/registros/',
  path: '/registros/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappSessionIdRoute =
  DashboardWhatsappSessionIdRouteImport.update({
    id: '/whatsapp/$sessionId',
    path: '/whatsapp/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardUsuariosNovoRoute = DashboardUsuariosNovoRouteImport.update({
  id: '/usuarios/novo',
  path: '/usuarios/novo',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/usuarios/novo': typeof DashboardUsuariosNovoRoute
  '/dashboard/whatsapp/$sessionId': typeof DashboardWhatsappSessionIdRoute
  '/dashboard/registros/': typeof DashboardRegistrosIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/usuarios/': typeof DashboardUsuariosIndexRoute
  '/dashboard/whatsapp/': typeof DashboardWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/usuarios/novo': typeof DashboardUsuariosNovoRoute
  '/dashboard/whatsapp/$sessionId': typeof DashboardWhatsappSessionIdRoute
  '/dashboard/registros': typeof DashboardRegistrosIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/usuarios': typeof DashboardUsuariosIndexRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/usuarios/novo': typeof DashboardUsuariosNovoRoute
  '/dashboard/whatsapp/$sessionId': typeof DashboardWhatsappSessionIdRoute
  '/dashboard/registros/': typeof DashboardRegistrosIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/usuarios/': typeof DashboardUsuariosIndexRoute
  '/dashboard/whatsapp/': typeof DashboardWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/usuarios/novo'
    | '/dashboard/whatsapp/$sessionId'
    | '/dashboard/registros/'
    | '/dashboard/settings/'
    | '/dashboard/usuarios/'
    | '/dashboard/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/usuarios/novo'
    | '/dashboard/whatsapp/$sessionId'
    | '/dashboard/registros'
    | '/dashboard/settings'
    | '/dashboard/usuarios'
    | '/dashboard/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/usuarios/novo'
    | '/dashboard/whatsapp/$sessionId'
    | '/dashboard/registros/'
    | '/dashboard/settings/'
    | '/dashboard/usuarios/'
    | '/dashboard/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp/': {
      id: '/dashboard/whatsapp/'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp/'
      preLoaderRoute: typeof DashboardWhatsappIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios/': {
      id: '/dashboard/usuarios/'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios/'
      preLoaderRoute: typeof DashboardUsuariosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/registros/': {
      id: '/dashboard/registros/'
      path: '/registros'
      fullPath: '/dashboard/registros/'
      preLoaderRoute: typeof DashboardRegistrosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp/$sessionId': {
      id: '/dashboard/whatsapp/$sessionId'
      path: '/whatsapp/$sessionId'
      fullPath: '/dashboard/whatsapp/$sessionId'
      preLoaderRoute: typeof DashboardWhatsappSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usuarios/novo': {
      id: '/dashboard/usuarios/novo'
      path: '/usuarios/novo'
      fullPath: '/dashboard/usuarios/novo'
      preLoaderRoute: typeof DashboardUsuariosNovoRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardUsuariosNovoRoute: typeof DashboardUsuariosNovoRoute
  DashboardWhatsappSessionIdRoute: typeof DashboardWhatsappSessionIdRoute
  DashboardRegistrosIndexRoute: typeof DashboardRegistrosIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUsuariosIndexRoute: typeof DashboardUsuariosIndexRoute
  DashboardWhatsappIndexRoute: typeof DashboardWhatsappIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardUsuariosNovoRoute: DashboardUsuariosNovoRoute,
  DashboardWhatsappSessionIdRoute: DashboardWhatsappSessionIdRoute,
  DashboardRegistrosIndexRoute: DashboardRegistrosIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUsuariosIndexRoute: DashboardUsuariosIndexRoute,
  DashboardWhatsappIndexRoute: DashboardWhatsappIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
